.TH "Logger" 3 "Wed Nov 3 2021" "Version 0.0.1" "nasapi-cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "enum LoggerStatus \fBgetStatus\fP ()"
.br
.ti -1c
.RI "void \fBsetStatus\fP (enum LoggerStatus newStatus)"
.br
.ti -1c
.RI "void \fBprintLog\fP (const std::string &log)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for nasapi-cpp from the source code\&.
