.TH "Query" 3 "Wed Nov 3 2021" "Version 0.0.1" "nasapi-cpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Query
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuery\fP (std::string &apiKey, enum QueryType type)"
.br
.ti -1c
.RI "void \fBApod\fP (const std::string &date='today', bool thumb=true)"
.br
.ti -1c
.RI "void \fBApod\fP (const std::string &startDate, const std::string &endDate, bool thumb)"
.br
.ti -1c
.RI "void \fBApod\fP (int count, bool thumb)"
.br
.ti -1c
.RI "const std::string & \fBgetQuery\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for nasapi-cpp from the source code\&.
